<?php
/**
 * @var \Favicode\ProductFaq\Block\Customer\ListCustomer $block
 * @var \Magento\Framework\Escaper $escaper
 */

$items = $block->getFaqs();
?>
<?php if ($items && count($items)): ?>
    <div class="table-wrapper reviews">
        <table class="data table table-reviews" id="my-reviews-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Product Reviews')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col date"><?= $escaper->escapeHtml(__('Created')) ?></th>
                    <th scope="col" class="col item"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                    <th scope="col" class="col summary"><?= $escaper->escapeHtml(__('Question')) ?></th>
                    <th scope="col" class="col description"><?= $escaper->escapeHtml(__('Answer')) ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($items as $faq): ?>
                    <tr>
                        <td data-th="<?= $escaper->escapeHtml(__('Created')) ?>" class="col date">
                            <?= $escaper->escapeHtml($block->dateFormat($faq->getCreatedAt())) ?>
                        </td>
                        <td data-th="<?= $escaper->escapeHtml(__('Product Name')) ?>" class="col item">
                            <strong class="product-name">
                                <a href="<?= $escaper->escapeHtml(__($block->getUrl($faq->getData('product_url')))) ?>">
                                    <?= $escaper->escapeHtml(__($faq->getData('product_name'))) ?>
                                </a>
                            </strong>
                        </td>
                        <td data-th="<?= $escaper->escapeHtml(__('Question')) ?>" class="col item">
                            <?= $escaper->escapeHtml(__($faq->getQuestion())) ?>
                        </td>
                        <td data-th="<?= $escaper->escapeHtml(__('Answer')) ?>" class="col item">
                            <?= $escaper->escapeHtml(__($faq->getAnswer())) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml(__('You have submitted no questions.')) ?></span></div>
<?php endif; ?>
